# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20160918_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='title'),
            preserve_default=False,
        ),
    ]
